[package]
name = "learn-cargo"
version = "0.1.0"
edition = "2024"

[dependencies]
# Windows平台的依赖
[target.'cfg(windows)'.dependencies]
log = "0.4"
env_logger = "0.10"

# Linux平台的依赖  
[target.'cfg(target_os = "linux")'.dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
